repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: name-tests-test
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: pretty-format-json
        args:
          - --autofix

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args:
          - --fix
          - --target-version=py312
          - --select=B,C,E,F,W,D
          - --line-length=80
          - --exclude=__init__.py

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
        - --ignore=E203,E402,E501,E800,W503,W391,E261
        - --select=B,C,E,F,W,T4,B9

  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
      - id: csslint
        args:
        - --format=compact
        - --ignore=adjoining-classes

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args:
          - --safe
          - --target-version=py312
          - --line-length=80
